using System;

namespace InSite.Persistence.Plugin.NCSHA
{
    [Serializable]
    public class HcProgram : IAnnualProgram
    {
        #region IAnnualProgram

        Guid? IAnnualProgram.AgencyIdentifier
        {
            get => AgencyGroupIdentifier;
            set => AgencyGroupIdentifier = (Guid)value;
        }

        Guid? IAnnualProgram.UserIdentifier
        {
            get => OwnerUserIdentifier;
            set => OwnerUserIdentifier = value;
        }

        #endregion

        public Guid? AgencyGroupIdentifier { get; set; }
        public Guid? OrganizationIdentifier { get; set; }
        public Guid? OwnerUserIdentifier { get; set; }

        public string FirstName { get; set; }
        public string HC001 { get; set; }
        public string HC002 { get; set; }
        public string HC003 { get; set; }
        public string HC004 { get; set; }
        public string HC005 { get; set; }
        public string HC006 { get; set; }
        public string HC007 { get; set; }
        public string HC008 { get; set; }
        public string HC009 { get; set; }
        public string HC010 { get; set; }
        public string HC011 { get; set; }
        public string HC012 { get; set; }
        public string HC013 { get; set; }
        public string HC014 { get; set; }
        public string HC015 { get; set; }
        public string HC016 { get; set; }
        public string HC017 { get; set; }
        public string HC018 { get; set; }
        public string HC019 { get; set; }
        public string HC020 { get; set; }
        public string HC021 { get; set; }
        public string HC022 { get; set; }
        public string HC023 { get; set; }
        public string HC024 { get; set; }
        public string HC025 { get; set; }
        public string HC026 { get; set; }
        public string HC027 { get; set; }
        public string HC028 { get; set; }
        public string HC029 { get; set; }
        public string HC030 { get; set; }
        public string HC031 { get; set; }
        public string HC032 { get; set; }
        public string HC033 { get; set; }
        public string HC034 { get; set; }
        public string HC035 { get; set; }
        public string HC036 { get; set; }
        public string HC037 { get; set; }
        public string HC038 { get; set; }
        public string HC039 { get; set; }
        public string HC040 { get; set; }
        public string HC041 { get; set; }
        public string HC042 { get; set; }
        public string HC043 { get; set; }
        public string HC044 { get; set; }
        public string HC045 { get; set; }
        public string HC046 { get; set; }
        public string HC047 { get; set; }
        public string HC048 { get; set; }
        public string HC049 { get; set; }
        public string HC050 { get; set; }
        public string HC051 { get; set; }
        public string HC052 { get; set; }
        public string HC053 { get; set; }
        public string HC054 { get; set; }
        public string HC055 { get; set; }
        public string HC056 { get; set; }
        public string HC057 { get; set; }
        public string HC058 { get; set; }
        public string HC059 { get; set; }
        public string HC060 { get; set; }
        public string HC061 { get; set; }
        public string HC062 { get; set; }
        public string HC063 { get; set; }
        public string HC064 { get; set; }
        public string HC065 { get; set; }
        public string HC066 { get; set; }
        public string HC067 { get; set; }
        public string HC068 { get; set; }
        public string HC069 { get; set; }
        public string HC070 { get; set; }
        public string HC071 { get; set; }
        public string HC072 { get; set; }
        public string HC073 { get; set; }
        public string HC074 { get; set; }
        public string HC075 { get; set; }
        public string HC076 { get; set; }
        public string HC077 { get; set; }
        public string HC078 { get; set; }
        public string HC079 { get; set; }
        public string HC082 { get; set; }
        public string HC083 { get; set; }
        public string HC084 { get; set; }
        public string HC085 { get; set; }
        public string HC086 { get; set; }
        public string HC087 { get; set; }
        public string HC088 { get; set; }
        public string HC089 { get; set; }
        public string HC090 { get; set; }
        public string HC091 { get; set; }
        public string HC094 { get; set; }
        public string HC095 { get; set; }
        public string HC096 { get; set; }
        public string HC097 { get; set; }
        public string HC098 { get; set; }
        public string HC099 { get; set; }
        public string HC100 { get; set; }
        public string HC101 { get; set; }
        public string HC102 { get; set; }
        public string HC103 { get; set; }
        public string HC104 { get; set; }
        public string HC105 { get; set; }
        public string HC106 { get; set; }
        public string HC107 { get; set; }
        public string HC108 { get; set; }
        public string HC109 { get; set; }
        public string HC110 { get; set; }
        public string HC111 { get; set; }
        public string HC112 { get; set; }
        public string HC113 { get; set; }
        public string HC114 { get; set; }
        public string HC115 { get; set; }
        public string HC116 { get; set; }
        public string HC117 { get; set; }
        public string HC118 { get; set; }
        public string HC119 { get; set; }
        public string HC120 { get; set; }
        public string HC121 { get; set; }
        public string HC122 { get; set; }
        public string HC123 { get; set; }
        public string HC124 { get; set; }
        public string HC125 { get; set; }
        public string HC126 { get; set; }
        public string HC127 { get; set; }
        public string HC128 { get; set; }
        public string HC129 { get; set; }
        public string HC130 { get; set; }
        public string HC131 { get; set; }
        public string HC132 { get; set; }
        public string HC133 { get; set; }
        public string HC134 { get; set; }
        public string HC141 { get; set; }
        public string HC142 { get; set; }
        public string HC143 { get; set; }
        public string HC144 { get; set; }
        public string HC145 { get; set; }
        public string HC146 { get; set; }
        public string HC147 { get; set; }
        public string HC148 { get; set; }
        public string HC149 { get; set; }
        public string HC150 { get; set; }
        public string HC151 { get; set; }
        public string HC152 { get; set; }
        public string HC153 { get; set; }
        public string HC154 { get; set; }
        public string HC155 { get; set; }
        public string HC156 { get; set; }
        public string HC157 { get; set; }
        public string HC158 { get; set; }
        public string HC159 { get; set; }
        public string HC160 { get; set; }
        public string HC161 { get; set; }
        public string HC162 { get; set; }
        public string HC163 { get; set; }
        public string HC164 { get; set; }
        public string HC165 { get; set; }
        public string HC166 { get; set; }
        public string HC167 { get; set; }
        public string HC168 { get; set; }
        public string HC169 { get; set; }
        public string HC170 { get; set; }
        public string HC171 { get; set; }
        public string HC172 { get; set; }
        public string HC173 { get; set; }
        public string HC174 { get; set; }
        public string HC175 { get; set; }
        public string HC176 { get; set; }
        public string HC177 { get; set; }
        public string HC178 { get; set; }
        public string HC179 { get; set; }
        public string HC180 { get; set; }
        public string HC181 { get; set; }
        public string HC182 { get; set; }
        public string HC183 { get; set; }
        public string HC184 { get; set; }
        public string HC185 { get; set; }
        public string HC186 { get; set; }
        public string HC187 { get; set; }
        public string HC188 { get; set; }
        public string HC189 { get; set; }
        public string HC190 { get; set; }
        public string HC191 { get; set; }
        public string HC193 { get; set; }
        public string HC194 { get; set; }
        public string HC195 { get; set; }
        public string HC196 { get; set; }
        public string HC207 { get; set; }
        public string HC208 { get; set; }
        public string HC209 { get; set; }
        public string HC210 { get; set; }
        public string HC211 { get; set; }
        public string HC212 { get; set; }
        public string HC213 { get; set; }
        public string HC214 { get; set; }
        public string HC215 { get; set; }
        public string HC216 { get; set; }
        public string HC217 { get; set; }
        public string HC218 { get; set; }
        public string HC219 { get; set; }
        public string HC220 { get; set; }
        public string HC221 { get; set; }
        public string HC222 { get; set; }
        public string HC223 { get; set; }
        public string HC224 { get; set; }
        public string HC225 { get; set; }
        public string HC226 { get; set; }
        public string HC227 { get; set; }
        public string HC228 { get; set; }
        public string HC229 { get; set; }
        public string HC230 { get; set; }
        public string HC231 { get; set; }
        public string HC232 { get; set; }
        public string HC233 { get; set; }
        public string HC234 { get; set; }
        public string HC235 { get; set; }
        public string HC236 { get; set; }
        public string HC237 { get; set; }
        public string HC238 { get; set; }
        public string HC239 { get; set; }
        public string HC240 { get; set; }
        public string HC241 { get; set; }
        public string HC242 { get; set; }
        public string HC243 { get; set; }
        public string HC244 { get; set; }
        public string HC245 { get; set; }
        public string HC246 { get; set; }
        public string HC247 { get; set; }
        public string HC248 { get; set; }
        public string HC249 { get; set; }
        public string HC250 { get; set; }
        public string HC251 { get; set; }
        public string HC252 { get; set; }
        public string HC253 { get; set; }
        public string HC254 { get; set; }
        public string HC255 { get; set; }
        public string HC256 { get; set; }
        public string HC257 { get; set; }
        public string HC258 { get; set; }
        public string HC259 { get; set; }
        public string HC260 { get; set; }
        public string HC261 { get; set; }
        public string HC262 { get; set; }
        public string HC263 { get; set; }
        public string HC264 { get; set; }
        public string HC265 { get; set; }
        public string HC266 { get; set; }
        public string HC267 { get; set; }
        public string HC268 { get; set; }
        public string HC269 { get; set; }
        public string HC270 { get; set; }
        public string HC271 { get; set; }
        public string HC272 { get; set; }
        public string HC273 { get; set; }
        public string HC274 { get; set; }
        public string HC275 { get; set; }
        public string HC276 { get; set; }
        public string HC277 { get; set; }
        public string HC278 { get; set; }
        public string HC279 { get; set; }
        public string HC280 { get; set; }
        public string HC281 { get; set; }
        public string HC282 { get; set; }
        public string HC283 { get; set; }
        public string HC284 { get; set; }
        public string HC285 { get; set; }
        public string HC286 { get; set; }
        public string HC287 { get; set; }
        public string HC288 { get; set; }
        public string HC289 { get; set; }
        public string HC290 { get; set; }
        public string HC291 { get; set; }
        public string HC292 { get; set; }
        public string HC293 { get; set; }
        public string HC294 { get; set; }
        public string HC295 { get; set; }
        public string HC296 { get; set; }
        public string HC297 { get; set; }
        public string HC298 { get; set; }
        public string HC299 { get; set; }
        public string HC300 { get; set; }
        public string HC301 { get; set; }
        public string HC302 { get; set; }
        public string HC303 { get; set; }
        public string HC304 { get; set; }
        public string HC305 { get; set; }
        public string HC306 { get; set; }
        public string HC307 { get; set; }
        public string HC308 { get; set; }
        public string HC309 { get; set; }
        public string HC310 { get; set; }
        public string HC312 { get; set; }
        public string HC313 { get; set; }
        public string HC314 { get; set; }
        public string HC315 { get; set; }
        public string HC316 { get; set; }
        public string HC317 { get; set; }
        public string HC318 { get; set; }
        public string HC319 { get; set; }
        public string HC320 { get; set; }
        public string HC321 { get; set; }
        public string HC322 { get; set; }
        public string HC323 { get; set; }
        public string HC324 { get; set; }
        public string HC325 { get; set; }
        public string HC326 { get; set; }
        public string HC327 { get; set; }
        public string HC328 { get; set; }
        public string HC329 { get; set; }
        public string HC330 { get; set; }
        public string HC331 { get; set; }
        public string HC332 { get; set; }
        public string HC333 { get; set; }
        public string HC334 { get; set; }
        public string HC335 { get; set; }
        public string HC336 { get; set; }
        public string HC337 { get; set; }
        public string HC338 { get; set; }
        public string HC339 { get; set; }
        public string HC340 { get; set; }
        public string HC341 { get; set; }
        public string HC342 { get; set; }
        public string HC343 { get; set; }
        public string HC344 { get; set; }
        public string HC345 { get; set; }
        public string HC346 { get; set; }
        public string HC347 { get; set; }
        public string HC348 { get; set; }
        public string HC349 { get; set; }
        public string HC350 { get; set; }
        public string HC351 { get; set; }
        public string HC352 { get; set; }
        public string HC353 { get; set; }
        public string HC354 { get; set; }
        public string HC355 { get; set; }
        public string HC356 { get; set; }
        public string HC357 { get; set; }
        public string InsertedBy { get; set; }
        public string LastName { get; set; }
        public string StateName { get; set; }
        public string UpdatedBy { get; set; }

        public bool IsVisibleOnTable01 { get; set; }
        public bool IsVisibleOnTable02 { get; set; }
        public bool IsVisibleOnTable03 { get; set; }
        public bool IsVisibleOnTable04 { get; set; }
        public bool IsVisibleOnTable05 { get; set; }
        public bool IsVisibleOnTable06 { get; set; }
        public bool IsVisibleOnTable07 { get; set; }
        public bool IsVisibleOnTable08 { get; set; }
        public bool IsVisibleOnTable09 { get; set; }
        public bool IsVisibleOnTable10 { get; set; }
        public bool IsVisibleOnTable11 { get; set; }
        public bool IsVisibleOnTable12 { get; set; }
        public bool IsVisibleOnTable13 { get; set; }
        public bool IsVisibleOnTable14 { get; set; }
        public bool IsVisibleOnTable15 { get; set; }
        public bool IsVisibleOnTable16 { get; set; }
        public bool IsVisibleOnTable17 { get; set; }
        public bool IsVisibleOnTable18 { get; set; }
        public bool IsVisibleOnTable19 { get; set; }
        public bool IsVisibleOnTable20 { get; set; }

        public int HcProgramId { get; set; }
        public int? ProgramFolderId { get; set; }
        public int? SourceId { get; set; }
        public int SurveyYear { get; set; }

        public DateTimeOffset? DateSubmitted { get; set; }
        public DateTimeOffset? DateTimeSaved { get; set; }
        public DateTimeOffset? DateTimeSubmitted { get; set; }
        public DateTimeOffset? Deadline { get; set; }
        public DateTimeOffset? InsertedOn { get; set; }
        public DateTimeOffset? UpdatedOn { get; set; }
    }
}