using System;

namespace InSite.UI.Lobby.Integrations.Prometric
{
    /// <summary>
    /// Prometric Weblaunch navigates to this page when the exam is started or restarted. The exam homepage supplies 
    /// parameters in the URL query string to the page. The parameters are specified in the Prometric service script 
    /// and from the appointment fields that are passed into the application via the test center administrative system.
    /// The parameters must also be called in the service script. The URL specified must NOT include the query string 
    /// since that string is generated by Prometric Weblaunch. 
    ///
    /// Example of a START Control Page URL
    /// https://example.com/examstart.aspx?user=xxx&amp;password=xxx&amp;examid=12&amp;candidateid=54
    ///
    /// </summary>
    public partial class Start : Layout.Lobby.LobbyBasePage
    {
        private LoginController _controller;

        protected override void OnInit(EventArgs e)
        {
            base.OnInit(e);

            _controller = new LoginController(Organization, ErrorMessage);

            SubmitButton.Click += SubmitButton_Click;
        }

        protected override void OnLoad(EventArgs e)
        {
            base.OnLoad(e);

            PersonCode.Text = Request.QueryString["user"];
            ExamEventPassword.Text = Request.QueryString["password"];

            Authenticate();
        }

        private void SubmitButton_Click(object sender, EventArgs e)
        {
            Authenticate();
        }

        private void Authenticate()
        {
            if (HasCredentials())
                _controller.Submit(PersonCode.Text.Trim(), ExamEventPassword.Text.Trim());
        }

        private bool HasCredentials()
        {
            return !string.IsNullOrWhiteSpace(PersonCode.Text) && !string.IsNullOrWhiteSpace(ExamEventPassword.Text);
        }
    }
}