//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated. 
// </auto-generated>
//------------------------------------------------------------------------------

namespace InSite.Admin.Accounts.Organizations.Controls
{


    public partial class Detail
    {

        /// <summary>
        /// NavPanel control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::InSite.Common.Web.UI.Nav NavPanel;

        /// <summary>
        /// OrganizationSection control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::InSite.Common.Web.UI.NavItem OrganizationSection;

        /// <summary>
        /// DetailOrganization control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::InSite.UI.Admin.Accounts.Organizations.Controls.DetailOrganization DetailOrganization;

        /// <summary>
        /// ConfigurationSection control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::InSite.Common.Web.UI.NavItem ConfigurationSection;

        /// <summary>
        /// DetailConfiguration control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::InSite.UI.Admin.Accounts.Organizations.Controls.DetailConfiguration DetailConfiguration;

        /// <summary>
        /// CollectionSection control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::InSite.Common.Web.UI.NavItem CollectionSection;

        /// <summary>
        /// CollectionManager control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::InSite.UI.Admin.Accounts.Organizations.Controls.CollectionManager CollectionManager;

        /// <summary>
        /// SubOrganizationsSection control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::InSite.Common.Web.UI.NavItem SubOrganizationsSection;

        /// <summary>
        /// ClearButton control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.HtmlControls.HtmlAnchor ClearButton;

        /// <summary>
        /// SubOrganizationFilterText control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::InSite.Common.Web.UI.TextBox SubOrganizationFilterText;

        /// <summary>
        /// SubOrganizationRepeater control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.Repeater SubOrganizationRepeater;

        /// <summary>
        /// DivisionsSection control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::InSite.Common.Web.UI.NavItem DivisionsSection;

        /// <summary>
        /// DivisionGrid control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::InSite.Admin.Accounts.Organizations.Controls.DivisionGrid DivisionGrid;

        /// <summary>
        /// DepartmentsSection control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::InSite.Common.Web.UI.NavItem DepartmentsSection;

        /// <summary>
        /// DepartmentGrid control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::InSite.Admin.Accounts.Organizations.Controls.DepartmentGrid DepartmentGrid;

        /// <summary>
        /// FieldsSection control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::InSite.Common.Web.UI.NavItem FieldsSection;

        /// <summary>
        /// UserProfileFieldsGrid control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::InSite.Admin.Accounts.Organizations.Controls.PortalFieldsGrid UserProfileFieldsGrid;

        /// <summary>
        /// ClassRegistrationFieldsGrid control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::InSite.Admin.Accounts.Organizations.Controls.PortalFieldsGrid ClassRegistrationFieldsGrid;

        /// <summary>
        /// LearnerDashboardFieldsGrid control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::InSite.Admin.Accounts.Organizations.Controls.PortalFieldsGrid LearnerDashboardFieldsGrid;

        /// <summary>
        /// InvoiceBillingAddressGrid control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::InSite.Admin.Accounts.Organizations.Controls.PortalFieldsGrid InvoiceBillingAddressGrid;
    }
}
