//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated. 
// </auto-generated>
//------------------------------------------------------------------------------

namespace InSite.UI.Portal.Home.Controls
{


    public partial class CmdsCompetencyDashboard
    {

        /// <summary>
        /// StatusAlert control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::InSite.Common.Web.UI.Alert StatusAlert;

        /// <summary>
        /// TitlePanel control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.HtmlControls.HtmlGenericControl TitlePanel;

        /// <summary>
        /// ShowWhat control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::InSite.Common.Web.UI.ComboBox ShowWhat;

        /// <summary>
        /// CmdsPrimaryProfilePanel control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.HtmlControls.HtmlGenericControl CmdsPrimaryProfilePanel;

        /// <summary>
        /// CmdsPrimaryProfileName control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.HtmlControls.HtmlGenericControl CmdsPrimaryProfileName;

        /// <summary>
        /// CmdsCompetencySummaryPanel control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.HtmlControls.HtmlGenericControl CmdsCompetencySummaryPanel;

        /// <summary>
        /// CmdsPrimaryCompetencySummary control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::InSite.UI.Portal.Home.Controls.CmdsCompetencySummary CmdsPrimaryCompetencySummary;

        /// <summary>
        /// CmdsSecondaryProfileContainer control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::InSite.Common.Web.UI.UpdatePanel CmdsSecondaryProfileContainer;

        /// <summary>
        /// CmdsSecondaryProfileSummary control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.Panel CmdsSecondaryProfileSummary;

        /// <summary>
        /// CmdsSecondaryCompetencySummary control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::InSite.UI.Portal.Home.Controls.CmdsCompetencySummary CmdsSecondaryCompetencySummary;

        /// <summary>
        /// CmdsSecondaryEmployeeProfile control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::InSite.Custom.CMDS.Common.Controls.Server.EmployeeProfileSelector CmdsSecondaryEmployeeProfile;

        /// <summary>
        /// CmdsLearningSummaryPanel control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::InSite.Common.Web.UI.Container CmdsLearningSummaryPanel;

        /// <summary>
        /// CmdsComplianceSummary control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::InSite.UI.Portal.Home.Controls.CmdsComplianceSummary CmdsComplianceSummary;

        /// <summary>
        /// CmdsLearningSummary control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::InSite.UI.Portal.Home.Controls.CmdsLearningSummary CmdsLearningSummary;

        /// <summary>
        /// CmdsOrientationSummary control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::InSite.UI.Portal.Home.Controls.CmdsOrientationSummary CmdsOrientationSummary;

        /// <summary>
        /// UserCompetencySummary control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::InSite.UI.Portal.Home.Controls.UserCompetencySummary UserCompetencySummary;
    }
}
