export interface ApiEventModel {
    AchievementIdentifier: string | null | undefined;
    EventIdentifier: string;
    LearnerRegistrationGroupIdentifier: string | null | undefined;
    MandatorySurveyFormIdentifier: string | null | undefined;
    OrganizationIdentifier: string;
    VenueCoordinatorIdentifier: string | null | undefined;
    VenueLocationIdentifier: string | null | undefined;
    VenueOfficeIdentifier: string | null | undefined;
    AllowMultipleRegistrations: boolean;
    AllowRegistrationWithLink: boolean | null | undefined;
    BillingCodeEnabled: boolean;
    IntegrationWithholdDistribution: boolean;
    IntegrationWithholdGrades: boolean;
    PersonCodeIsRequired: boolean;
    WaitlistEnabled: boolean;
    AppointmentType: string;
    Content: string;
    DistributionCode: string;
    DistributionErrors: string;
    DistributionProcess: string;
    DistributionStatus: string;
    DurationUnit: string;
    EventBillingType: string;
    EventCalendarColor: string;
    EventClassCode: string;
    EventDescription: string;
    EventFormat: string;
    EventPublicationStatus: string;
    EventRequisitionStatus: string;
    EventSchedulingStatus: string;
    EventSource: string;
    EventSummary: string;
    EventTitle: string;
    EventType: string;
    ExamMaterialReturnShipmentCode: string;
    ExamMaterialReturnShipmentCondition: string;
    ExamScoreWarnings: string;
    ExamType: string;
    LastChangeType: string;
    LastChangeUser: string;
    PublicationErrors: string;
    RegistrationFields: string;
    VenueRoom: string;
    CapacityMaximum: number | null | undefined;
    CapacityMinimum: number | null | undefined;
    DurationQuantity: number | null | undefined;
    EventNumber: number;
    ExamDurationInMinutes: number | null | undefined;
    InvigilatorMinimum: number | null | undefined;
    CreditHours: number | null | undefined;
    DistributionExpected: string | null | undefined;
    DistributionOrdered: string | null | undefined;
    DistributionShipped: string | null | undefined;
    DistributionTracked: string | null | undefined;
    EventScheduledEnd: string | null | undefined;
    EventScheduledStart: string;
    ExamMaterialReturnShipmentReceived: string | null | undefined;
    ExamStarted: string | null | undefined;
    LastChangeTime: string | null | undefined;
    RegistrationDeadline: string | null | undefined;
    RegistrationLocked: string | null | undefined;
    RegistrationStart: string | null | undefined
}