using System;

namespace InSite.Persistence.Plugin.CMDS
{
    public class ZUserStatus
    {
        public int? CountRQ_Requirement { get; set; }
        public int? CountVA_Requirement { get; set; }
        public int? CountRQ_Code { get; set; }
        public int? CountVA_Code { get; set; }
        public int? CountEX_Competency { get; set; }
        public int? CountNT_Competency { get; set; }
        public int? CountNA_Competency { get; set; }
        public int? CountNC_Competency { get; set; }
        public int? CountRQ_Competency { get; set; }
        public int? CountSA_Competency { get; set; }
        public int? CountSV_Competency { get; set; }
        public int? CountVA_Competency { get; set; }
        public int? CountEX_CompetencyCritical { get; set; }
        public int? CountNT_CompetencyCritical { get; set; }
        public int? CountNA_CompetencyCritical { get; set; }
        public int? CountNC_CompetencyCritical { get; set; }
        public int? CountRQ_CompetencyCritical { get; set; }
        public int? CountSA_CompetencyCritical { get; set; }
        public int? CountSV_CompetencyCritical { get; set; }
        public int? CountVA_CompetencyCritical { get; set; }
        public int? CountEX_CompetencyCriticalMandatory { get; set; }
        public int? CountNT_CompetencyCriticalMandatory { get; set; }
        public int? CountNA_CompetencyCriticalMandatory { get; set; }
        public int? CountNC_CompetencyCriticalMandatory { get; set; }
        public int? CountRQ_CompetencyCriticalMandatory { get; set; }
        public int? CountSA_CompetencyCriticalMandatory { get; set; }
        public int? CountSV_CompetencyCriticalMandatory { get; set; }
        public int? CountVA_CompetencyCriticalMandatory { get; set; }
        public Guid DepartmentIdentifier { get; set; }
        public int? CountRQ_Document { get; set; }
        public int? CountVA_Document { get; set; }
        public int? CountRQ_Module { get; set; }
        public int? CountVA_Module { get; set; }
        public int? CountEX_CompetencyNoncritical { get; set; }
        public int? CountNT_CompetencyNoncritical { get; set; }
        public int? CountNA_CompetencyNoncritical { get; set; }
        public int? CountNC_CompetencyNoncritical { get; set; }
        public int? CountRQ_CompetencyNoncritical { get; set; }
        public int? CountSA_CompetencyNoncritical { get; set; }
        public int? CountSV_CompetencyNoncritical { get; set; }
        public int? CountVA_CompetencyNoncritical { get; set; }
        public int? CountEX_CompetencyNoncriticalMandatory { get; set; }
        public int? CountNT_CompetencyNoncriticalMandatory { get; set; }
        public int? CountNA_CompetencyNoncriticalMandatory { get; set; }
        public int? CountNC_CompetencyNoncriticalMandatory { get; set; }
        public int? CountRQ_CompetencyNoncriticalMandatory { get; set; }
        public int? CountSA_CompetencyNoncriticalMandatory { get; set; }
        public int? CountSV_CompetencyNoncriticalMandatory { get; set; }
        public int? CountVA_CompetencyNoncriticalMandatory { get; set; }
        public Guid? PrimaryProfileIdentifier { get; set; }
        public int? CountRQ_Practice { get; set; }
        public int? CountVA_Practice { get; set; }
        public int? CountRQ_Procedure { get; set; }
        public int? CountVA_Procedure { get; set; }
        public Guid? OrganizationIdentifier { get; set; }
        public int? CountRQ_Certificate { get; set; }
        public int? CountVA_Certificate { get; set; }
        public int? CountRQ_Guide { get; set; }
        public int? CountVA_Guide { get; set; }
        public int SnapshotKey { get; set; }
        public Guid UserIdentifier { get; set; }

        public DateTime AsAt { get; set; }

        public decimal? Score_Requirement { get; set; }
        public decimal? Score_Code { get; set; }
        public decimal? ScoreEX_Competency { get; set; }
        public decimal? ScoreNT_Competency { get; set; }
        public decimal? ScoreNA_Competency { get; set; }
        public decimal? ScoreNC_Competency { get; set; }
        public decimal? ScoreRQ_Competency { get; set; }
        public decimal? ScoreSA_Competency { get; set; }
        public decimal? ScoreSV_Competency { get; set; }
        public decimal? ScoreVA_Competency { get; set; }
        public decimal? Score_Competency { get; set; }
        public decimal? ScoreEX_CompetencyCritical { get; set; }
        public decimal? ScoreNT_CompetencyCritical { get; set; }
        public decimal? ScoreNA_CompetencyCritical { get; set; }
        public decimal? ScoreNC_CompetencyCritical { get; set; }
        public decimal? ScoreRQ_CompetencyCritical { get; set; }
        public decimal? ScoreSA_CompetencyCritical { get; set; }
        public decimal? ScoreSV_CompetencyCritical { get; set; }
        public decimal? ScoreVA_CompetencyCritical { get; set; }
        public decimal? Score_CompetencyCritical { get; set; }
        public decimal? ScoreEX_CompetencyCriticalMandatory { get; set; }
        public decimal? ScoreNT_CompetencyCriticalMandatory { get; set; }
        public decimal? ScoreNA_CompetencyCriticalMandatory { get; set; }
        public decimal? ScoreNC_CompetencyCriticalMandatory { get; set; }
        public decimal? ScoreSA_CompetencyCriticalMandatory { get; set; }
        public decimal? ScoreSV_CompetencyCriticalMandatory { get; set; }
        public decimal? ScoreVA_CompetencyCriticalMandatory { get; set; }
        public decimal? Score_CompetencyCriticalMandatory { get; set; }
        public decimal? Score_Document { get; set; }
        public decimal? Score_Module { get; set; }
        public decimal? ScoreEX_CompetencyNoncritical { get; set; }
        public decimal? ScoreNT_CompetencyNoncritical { get; set; }
        public decimal? ScoreNA_CompetencyNoncritical { get; set; }
        public decimal? ScoreNC_CompetencyNoncritical { get; set; }
        public decimal? ScoreRQ_CompetencyNoncritical { get; set; }
        public decimal? ScoreSA_CompetencyNoncritical { get; set; }
        public decimal? ScoreSV_CompetencyNoncritical { get; set; }
        public decimal? ScoreVA_CompetencyNoncritical { get; set; }
        public decimal? Score_CompetencyNoncritical { get; set; }
        public decimal? ScoreEX_CompetencyNoncriticalMandatory { get; set; }
        public decimal? ScoreNT_CompetencyNoncriticalMandatory { get; set; }
        public decimal? ScoreNA_CompetencyNoncriticalMandatory { get; set; }
        public decimal? ScoreNC_CompetencyNoncriticalMandatory { get; set; }
        public decimal? ScoreSA_CompetencyNoncriticalMandatory { get; set; }
        public decimal? ScoreSV_CompetencyNoncriticalMandatory { get; set; }
        public decimal? ScoreVA_CompetencyNoncriticalMandatory { get; set; }
        public decimal? Score_CompetencyNoncriticalMandatory { get; set; }
        public decimal? Score_Practice { get; set; }
        public decimal? Score_Procedure { get; set; }
        public decimal? Score_Certificate { get; set; }
        public decimal? Score_Guide { get; set; }
    }
}
