//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated. 
// </auto-generated>
//------------------------------------------------------------------------------

namespace InSite.Admin.Contacts.People.Controls
{


    public partial class SearchCriteria
    {

        /// <summary>
        /// FullName control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::InSite.Common.Web.UI.TextBox FullName;

        /// <summary>
        /// FirstName control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::InSite.Common.Web.UI.TextBox FirstName;

        /// <summary>
        /// LastName control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::InSite.Common.Web.UI.TextBox LastName;

        /// <summary>
        /// NameFilterType control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::InSite.Common.Web.UI.ComboBox NameFilterType;

        /// <summary>
        /// Code control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::InSite.Common.Web.UI.TextBox Code;

        /// <summary>
        /// CommentKeyword control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::InSite.Common.Web.UI.TextBox CommentKeyword;

        /// <summary>
        /// Gender control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::InSite.Common.Web.UI.GenderComboBox Gender;

        /// <summary>
        /// Issues control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::InSite.Common.Web.UI.ComboBox Issues;

        /// <summary>
        /// CommentFlags control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::InSite.Common.Web.UI.MultiComboBox CommentFlags;

        /// <summary>
        /// Email control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::InSite.Common.Web.UI.TextBox Email;

        /// <summary>
        /// EmailAlternate control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::InSite.Common.Web.UI.TextBox EmailAlternate;

        /// <summary>
        /// EmailEnabledField control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.HtmlControls.HtmlGenericControl EmailEnabledField;

        /// <summary>
        /// EmailEnabled control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::InSite.Common.Web.UI.ComboBox EmailEnabled;

        /// <summary>
        /// EmailStatusField control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.HtmlControls.HtmlGenericControl EmailStatusField;

        /// <summary>
        /// EmailStatus control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::InSite.Common.Web.UI.ComboBox EmailStatus;

        /// <summary>
        /// EmailVerified control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::InSite.Common.Web.UI.ComboBox EmailVerified;

        /// <summary>
        /// SearchButton control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::InSite.Common.Web.UI.FilterButton SearchButton;

        /// <summary>
        /// ClearButton control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::InSite.Common.Web.UI.ClearButton ClearButton;

        /// <summary>
        /// EmployerUpdatePanel control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::InSite.Common.Web.UI.UpdatePanel EmployerUpdatePanel;

        /// <summary>
        /// EmployerParentGroupID control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::InSite.Common.Web.UI.FindGroup EmployerParentGroupID;

        /// <summary>
        /// EmployerGroupID control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::InSite.Common.Web.UI.FindGroup EmployerGroupID;

        /// <summary>
        /// JobTitle control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::InSite.Common.Web.UI.TextBox JobTitle;

        /// <summary>
        /// AccountStatusId control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::InSite.Common.Web.UI.ItemIdMultiComboBox AccountStatusId;

        /// <summary>
        /// IsApproved control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::InSite.Common.Web.UI.ComboBox IsApproved;

        /// <summary>
        /// IsArchived control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::InSite.Common.Web.UI.ComboBox IsArchived;

        /// <summary>
        /// IsMultiOrganization control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::InSite.Common.Web.UI.ComboBox IsMultiOrganization;

        /// <summary>
        /// OrganizationRole control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::InSite.Common.Web.UI.OrganizationRoleMultiComboBox OrganizationRole;

        /// <summary>
        /// ValidAchievementIdentifier control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::InSite.Common.Web.UI.FindAchievement ValidAchievementIdentifier;

        /// <summary>
        /// AddressType control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::InSite.Common.Web.UI.PersonAddressTypeMultiComboBox AddressType;

        /// <summary>
        /// Country control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::InSite.Common.Web.UI.OrganizationPersonCountryComboBox Country;

        /// <summary>
        /// Province control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::InSite.Common.Web.UI.OrganizationPersonProvinceMultiComboBox Province;

        /// <summary>
        /// City control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::InSite.Common.Web.UI.OrganizationPersonCityMultiComboBox City;

        /// <summary>
        /// Phone control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::InSite.Common.Web.UI.TextBox Phone;

        /// <summary>
        /// RegionField control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.HtmlControls.HtmlGenericControl RegionField;

        /// <summary>
        /// Region control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::InSite.Common.Web.UI.ItemNameComboBox Region;

        /// <summary>
        /// GroupsUpdatePanel control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::InSite.Common.Web.UI.UpdatePanel GroupsUpdatePanel;

        /// <summary>
        /// MembershipGroupID control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::InSite.Common.Web.UI.FindGroup MembershipGroupID;

        /// <summary>
        /// GroupMembershipDateField control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.HtmlControls.HtmlGenericControl GroupMembershipDateField;

        /// <summary>
        /// GroupMembershipDate control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::InSite.Common.Web.UI.DateTimeOffsetSelector GroupMembershipDate;

        /// <summary>
        /// ExcludeMembershipGroupID control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::InSite.Common.Web.UI.FindGroup ExcludeMembershipGroupID;

        /// <summary>
        /// ShowColumns control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::InSite.Common.Web.UI.MultiComboBox ShowColumns;

        /// <summary>
        /// SortColumns control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::InSite.Common.Web.UI.ComboBox SortColumns;

        /// <summary>
        /// FilterManager control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::InSite.UI.Layout.Common.Controls.SearchCriteriaFilterManager FilterManager;

        /// <summary>
        /// CreatedSince control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::InSite.Common.Web.UI.DateTimeOffsetSelector CreatedSince;

        /// <summary>
        /// CreatedBefore control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::InSite.Common.Web.UI.DateTimeOffsetSelector CreatedBefore;

        /// <summary>
        /// ModifiedSince control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::InSite.Common.Web.UI.DateTimeOffsetSelector ModifiedSince;

        /// <summary>
        /// ModifiedBefore control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::InSite.Common.Web.UI.DateTimeOffsetSelector ModifiedBefore;

        /// <summary>
        /// LastAuthenticatedSince control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::InSite.Common.Web.UI.DateTimeOffsetSelector LastAuthenticatedSince;

        /// <summary>
        /// LastAuthenticatedBefore control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::InSite.Common.Web.UI.DateTimeOffsetSelector LastAuthenticatedBefore;
    }
}
